#!/bin/bash
set -e
set -u

function link_dir {
    local src="${1}"
    local dest="${2}"
    local prefix="${3}"

    for path in $(find "${src}" -type f -depth 1); do
        name="$(basename "${path}")"
        local link="${dest}/${prefix}${name}"

        rm -f "${link}"
        ln -s "${path}" "${link}"
    done

    while read -r path; do
        IFS=/ read -r -a parts <<< "${path/${src}\//}"

        local first_part="${parts[0]}"
        if [[ "${first_part}" != "Library" ]]; then
            parts[0]="${prefix}${first_part}"
        fi

        local link="${dest}/$(IFS=/; echo "${parts[*]}")"
        local link_dir="$(dirname "${link}")"

        mkdir -p "${link_dir}"
        rm -rf "${link}"
        ln -s "${path}" "${link}"
    done < <(find "${src}" -type f -mindepth 2 -exec "dirname" "{}" + | sort | uniq)
    exit 0


    local src="${1}"
    local dest="${2}"
    local prefix="${3}"
    local ignores="${4}"
    local name

    for path in "${src}/"*; do
        name="$(basename "${path}")"
        local link="${dest}/${prefix}${name}"

        if [[ "$(list_contains "${ignores}" "${name}")" != "" ]]; then
            continue
        fi

        if [[ "${name}" == "config" ]]; then
            mkdir -p "${link}"

            for path in "${path}/"*; do
                name="$(basename "${path}")"
                local link="${link}/${name}"
                echo "${path} ${name} ${link}"

                rm -rf "${link}"
                ln -s "${path}" "${link}"
            done
        else
            rm -rf "${link}"
            ln -s "${path}" "${link}"
        fi
    done
}

src="${1}"
dest="${2}"
prefix="${3:-""}"

if [[ -d "${src}" ]]; then
    link_dir "${src}" "${dest}" "${prefix}" ""
fi
