[tools]
"aqua:gleam-lang/gleam" = "latest"
"asdf:mise-plugins/mise-elixir-ls" = "latest"
"asdf:mise-plugins/mise-rebar" = "latest"
elixir = "latest"
erlang = "latest"
go = "latest"
python = "latest"
rust = "latest"
"aqua:pypa/pipx" = "latest"
"pipx:yawsso" = "latest"
node = "latest"
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = ["go", "elixir", "erlang", "ruby", "node", "python", "rust", "gleam"]
