source ~/.vim/plugins.vim
source ~/.vim/functions.vim

call InitState(expand("~/.vim/state"))

" Behavior
set backspace=indent,eol,start
set backupext=.bak
set clipboard^=unnamed,unnamedplus
set cursorbind
set hidden
set history=100
set ignorecase
set incsearch
set laststatus=2
set scrolljump=5
set scrolloff=5
set sidescrolloff=5
set shortmess=aoOtT
set showmatch
set noshowmode
set smartcase
set nospell
set timeout
set ttimeout
set timeoutlen=100
set ttimeoutlen=20
set undofile
set undolevels=2000
set viewoptions=cursor,folds,slash,unix
set virtualedit=onemore
set whichwrap=b,s,<,>,[,]
set wildignore+=node_modules,.git,log,vendor,tmp,temp,*.so,*.o,*.a,*.test
set wildmenu
set wildmode=list:longest,full
set nowrap
let g:skipview_files = ['\.git', 'node_modules', 'log', 'vendor', 'tmp', 'temp']

" Formatting
set endofline
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=8
augroup Formatting
    autocmd!
    autocmd BufWritePre <buffer> call StripWhitespace()
augroup END

" UI
set t_Co=256
set background=dark
filetype plugin indent on
syntax on
set termguicolors
colorscheme dracula
source ~/.vim/colors.vim
set cursorline
set foldlevelstart=99
set foldmethod=syntax
set hlsearch
set list
set listchars=tab:›\ ,trail:•,extends:#,precedes:#,nbsp:∙
set mouse=a
set mousefocus
set mousehide
set number

" Key Mappings
let mapleader = ','
noremap <silent> <leader>/ :nohlsearch<CR>
noremap <silent> <leader>n :NumbersToggle<CR>

" Plugin Settings
let g:autoclose_vim_commentmode = 1
let g:airline_powerline_fonts = 1
let g:airline#extensions#ale#enabled = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_linters = {'go': ['gopls', 'govet']}
let g:ale_sign_error = '✕'
let g:ale_sign_warning = '!'
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_fmt_command = "goimports"
let g:go_highlight_extra_types = 1
let g:go_highlight_trailing_whitespace_error = 0
let g:go_highlight_operators = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_string_spellcheck = 0
let g:rustfmt_autosave = 1
